export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_START = 'FETCH_FOODS_START';
export const FETCH_FOODS_ERROR = 'FETCH_FOODS_ERROR';
export const FILTER_FOOD_ITEMS = 'FILTER_FOOD_ITEMS';
